server:
  port: 8084
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.75.129:3306/guli_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    host: 192.168.75.129
  rabbitmq:
    host: 192.168.75.129
    virtual-host: /shang
    username: shang
    password: shang
mybatis-plus:
  mapper-locations: classpath:mapper/oms/*.xml  # 读取映射文件
  global-config:
    db-config:
      id-type: auto  # 默认使用数据库自增